name: frontend_app
description: A new Flutter project.
publish_to: none
version: 1.0.9+9
environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  open_filex: ^4.5.0
  path_provider: ^2.1.4
  universal_io: ^2.2.2
  pdf: ^3.11.0
  share_plus: ^10.0.2
  url_launcher: ^6.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
  - assets/images/logoLL.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logoLL.png
  min_sdk_android: 21
  remove_alpha_ios: true
